"""create table

Revision ID: 41c24ce68bae
Revises: 21d96c716c6a
Create Date: 2025-02-03 08:24:20.289757

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "41c24ce68bae"
down_revision: Union[str, None] = "21d96c716c6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
