"""create table

Revision ID: 83d7357df2f3
Revises: 71f3a681f0bb
Create Date: 2025-01-11 16:56:44.648118

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "83d7357df2f3"
down_revision: Union[str, None] = "71f3a681f0bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chats", "updated_at")
    op.add_column("messages", sa.Column("input_message", sa.String(), nullable=False))
    op.add_column("messages", sa.Column("output_message", sa.String(), nullable=False))
    op.drop_column("messages", "updated_at")
    op.drop_column("messages", "chat_message")
    op.drop_column("messages", "sender")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "sender",
            postgresql.ENUM("user", "bot", name="sendertype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "messages",
        sa.Column("chat_message", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "messages",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("messages", "output_message")
    op.drop_column("messages", "input_message")
    op.add_column(
        "chats",
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
