"""create table

Revision ID: f6927455feec
Revises: e7100f3623c8
Create Date: 2025-02-07 08:16:05.071623

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6927455feec"
down_revision: Union[str, None] = "e7100f3623c8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "conversations",
        "user_id",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "current_profiles",
        "user_id",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.create_unique_constraint(None, "current_profiles", ["user_id"])
    op.alter_column(
        "future_profiles",
        "user_id",
        existing_type=sa.BIGINT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "future_profiles",
        "user_id",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "current_profiles", type_="unique")
    op.alter_column(
        "current_profiles",
        "user_id",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.alter_column(
        "conversations",
        "user_id",
        existing_type=sa.String(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
