"""create table

Revision ID: fe2e5cc695cc
Revises: f6927455feec
Create Date: 2025-02-08 03:29:12.122614

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fe2e5cc695cc"
down_revision: Union[str, None] = "f6927455feec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "current_profiles_user_id_key", "current_profiles", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "current_profiles_user_id_key", "current_profiles", ["user_id"]
    )
    # ### end Alembic commands ###
